eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway2
  config:
    import: optional:configserver:http://localhost:8088
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          id: cars
          uri: http://localhost:8081
          predicates:
            Path=/api/vehicle/**

